"""run model column and tenant/created index

Revision ID: 484bc9c693ac
Revises: 8c6d70bc2934
Create Date: 2026-09-10 18:08:37.535386

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '484bc9c693ac'
down_revision: str | None = '8c6d70bc2934'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('model', sa.String(length=60), nullable=True))
    # Create before dropping: tenant_id is a prefix of the new index, so there is never a
    # moment where a tenant's runs are unindexed.
    op.create_index('ix_runs_tenant_created', 'runs', ['tenant_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runs_tenant_created', table_name='runs')
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.drop_column('runs', 'model')
    # ### end Alembic commands ###
