"""run chart

Revision ID: 0fe15064cf2d
Revises: 484bc9c693ac
Create Date: 2026-09-10 18:32:31.191181

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0fe15064cf2d'
down_revision: str | None = '484bc9c693ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('chart', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'chart')
    # ### end Alembic commands ###
