"""run trace

Revision ID: 62162b953aa7
Revises: 0f6da5ee636c
Create Date: 2026-09-18 12:52:40.259934

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '62162b953aa7'
down_revision: str | None = '0f6da5ee636c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('trace', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'trace')
    # ### end Alembic commands ###
